use keyring::Entry;

/// Credential storage, backed by Windows Credential Manager.
///
/// The important property here is what is *missing*: there is no command that
/// returns a secret. `secret_get` used to be one, which meant the webview -
/// the part of the app that renders untrusted project content and talks to the
/// network - could ask for the GitHub token and get it. Now the token never
/// leaves Rust: the frontend asks for an *operation*, and this module hands the
/// credential to the HTTP or Git layer directly.
///
/// Credentials are filed per GitHub account rather than under one global key,
/// because an administrator can legitimately have more than one account and a
/// shared token is not supported.
const SERVICE: &str = "DinoDepotStudio";

/// The key the single-account build used. Read for the benefit of anyone
/// upgrading; never written.
pub const LEGACY_GITHUB_KEY: &str = "github-token";

/// The key the single-webhook build used.
///
/// A Discord webhook points at one channel in one server, which belongs to one
/// cluster - so it belongs to one *project*, and a global key meant a freshly
/// created project opened Settings already claiming to have a webhook stored,
/// and posted its announcements into somebody else's channel. Read so an
/// upgrade can adopt it into a project the administrator names; never written.
pub const LEGACY_DISCORD_WEBHOOK_KEY: &str = "discord-webhook";

fn entry(key: &str) -> Result<Entry, String> {
    Entry::new(SERVICE, key).map_err(|e| e.to_string())
}

/// The credential key for a GitHub account id.
pub fn github_key(account_id: &str) -> String {
    format!("github-account:{account_id}")
}

/// The credential key for a project's Discord webhook.
pub fn discord_webhook_key(project_id: &str) -> String {
    format!("discord-webhook:{project_id}")
}

/// Whether an id may be used as the tail of a namespaced credential key.
///
/// Project ids and GitHub account ids are both generated by the app, but they
/// arrive here from files that can be edited by hand, so neither is trusted to
/// be well formed.
fn is_safe_id(id: &str) -> bool {
    !id.is_empty()
        && id.len() <= 64
        && id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

/// Keys the frontend is allowed to name.
///
/// An allowlist rather than a sanitizer: the frontend has no business inventing
/// credential keys, and a fixed set means a compromised page cannot enumerate
/// or overwrite entries belonging to anything else on the machine.
fn is_allowed_key(key: &str) -> bool {
    if key == LEGACY_DISCORD_WEBHOOK_KEY || key == LEGACY_GITHUB_KEY {
        return true;
    }
    if let Some(id) = key.strip_prefix("github-account:") {
        return is_safe_id(id);
    }
    match key.strip_prefix("discord-webhook:") {
        Some(id) => is_safe_id(id),
        None => false,
    }
}

fn check_key(key: &str) -> Result<(), String> {
    if is_allowed_key(key) {
        Ok(())
    } else {
        Err(format!("'{key}' is not a credential this app manages"))
    }
}

#[tauri::command]
pub fn secret_set(key: String, value: String) -> Result<(), String> {
    check_key(&key)?;
    if value.trim().is_empty() {
        return Err("A credential cannot be empty".into());
    }
    entry(&key)?.set_password(&value).map_err(|e| e.to_string())
}

/// Reads a secret. Deliberately **not** a Tauri command - see the module note.
pub fn secret_read(key: &str) -> Result<Option<String>, String> {
    match entry(key)?.get_password() {
        Ok(v) => Ok(Some(v)),
        Err(keyring::Error::NoEntry) => Ok(None),
        Err(e) => Err(e.to_string()),
    }
}

/// Whether a credential exists. The only thing the frontend may learn about one.
#[tauri::command]
pub fn secret_has(key: String) -> Result<bool, String> {
    check_key(&key)?;
    Ok(secret_read(&key)?.is_some())
}

#[tauri::command]
pub fn secret_delete(key: String) -> Result<(), String> {
    check_key(&key)?;
    match entry(&key)?.delete_credential() {
        Ok(()) | Err(keyring::Error::NoEntry) => Ok(()),
        Err(e) => Err(e.to_string()),
    }
}

/// The webhook for a project. `None` when that project has never been given one.
///
/// Deliberately no fallback to {@link LEGACY_DISCORD_WEBHOOK_KEY}: falling back
/// is exactly the behaviour that posted one cluster's announcements into
/// another's channel. The legacy entry is adopted explicitly instead.
pub fn discord_webhook(project_id: &str) -> Result<Option<String>, String> {
    if !is_safe_id(project_id) {
        return Err("A webhook is stored against a project, and this one has no usable id".into());
    }
    secret_read(&discord_webhook_key(project_id))
}

/// Moves a webhook stored by an older build into the named project.
///
/// One-way and one-time: the legacy entry is deleted, so the next project that
/// opens Settings is not offered the same webhook a second time.
#[tauri::command]
pub fn discord_webhook_adopt_legacy(project_id: String) -> Result<(), String> {
    if !is_safe_id(&project_id) {
        return Err("A webhook is stored against a project, and this one has no usable id".into());
    }
    let webhook = secret_read(LEGACY_DISCORD_WEBHOOK_KEY)?
        .ok_or("There is no webhook from an older version to move")?;
    entry(&discord_webhook_key(&project_id))?
        .set_password(&webhook)
        .map_err(|e| e.to_string())?;
    // Only after the copy has landed: losing the credential outright is worse
    // than being offered it twice.
    match entry(LEGACY_DISCORD_WEBHOOK_KEY)?.delete_credential() {
        Ok(()) | Err(keyring::Error::NoEntry) => Ok(()),
        Err(e) => Err(e.to_string()),
    }
}

/// The GitHub token for an account, falling back to the pre-multi-account key.
///
/// The fallback is what stops an upgrade from silently logging everybody out;
/// it disappears once the account binding flow has run.
pub fn github_token(account_id: &str) -> Result<String, String> {
    if !account_id.is_empty() {
        if let Some(token) = secret_read(&github_key(account_id))? {
            return Ok(token);
        }
    }
    if let Some(token) = secret_read(LEGACY_GITHUB_KEY)? {
        return Ok(token);
    }
    Err("No GitHub sign-in stored - connect your GitHub account in Settings".into())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn account_keys_are_namespaced() {
        assert_eq!(github_key("12345"), "github-account:12345");
    }

    #[test]
    fn webhook_keys_are_namespaced_by_project() {
        assert_eq!(
            discord_webhook_key("11111111-2222-4333-8444-555555555555"),
            "discord-webhook:11111111-2222-4333-8444-555555555555"
        );
    }

    #[test]
    fn the_allowlist_covers_what_the_app_actually_stores() {
        assert!(is_allowed_key(LEGACY_DISCORD_WEBHOOK_KEY));
        assert!(is_allowed_key(LEGACY_GITHUB_KEY));
        assert!(is_allowed_key("github-account:1234567"));
        assert!(is_allowed_key("github-account:abc-DEF_9"));
        assert!(is_allowed_key("discord-webhook:11111111-2222-4333-8444-555555555555"));
    }

    /// A project with no id must not be able to reach the legacy entry by
    /// naming an empty tail - that is the global webhook all over again.
    #[test]
    fn a_webhook_key_needs_a_real_project_id() {
        assert!(!is_allowed_key("discord-webhook:"));
        assert!(!is_allowed_key("discord-webhook:has space"));
        assert!(!is_allowed_key("discord-webhook:../../other"));
        assert!(discord_webhook("").is_err());
    }

    /// The frontend must not be able to name an entry belonging to anything
    /// else, nor to sweep the store looking for one.
    #[test]
    fn anything_else_is_refused() {
        for bad in [
            "",
            "github-account:",
            "github-account:has space",
            "github-account:../../other",
            "*",
            "some-other-app-token",
            "GitHub-Account:1",
        ] {
            assert!(!is_allowed_key(bad), "{bad} should be refused");
        }
    }

    #[test]
    fn an_over_long_account_id_is_refused() {
        assert!(!is_allowed_key(&format!("github-account:{}", "1".repeat(65))));
    }

    #[test]
    fn empty_values_are_refused_rather_than_stored() {
        assert!(secret_set("discord-webhook".into(), "   ".into()).is_err());
    }
}
