import { describe, expect, it } from "vitest";
import { issuesFor, validateProject, type ValidationInput } from "./project";
import { defaultProjectSettings, type ProjectSettings } from "../model/project";
import { emptyProductionDraft } from "../model/production";
import { emptyRemapsDraft } from "../model/remaps";
import { emptyCosmeticsDraft, type CosmeticsDraft } from "../model/cosmetics";
import { emptyCatalog, type CatalogFile } from "../model/catalog";
import { emptyPlayers, newPlayer, type PlayersFile } from "../model/players";

/**
 * The one place that says whether a project is fit to publish.
 *
 * Errors block; warnings can be acknowledged. The split matters: plenty of
 * warnings are "this looks unusual" rather than "this is wrong", and a cluster
 * with an unusual setup should still be able to publish.
 */

const settings = (over: Partial<ProjectSettings> = {}): ProjectSettings => ({
  ...defaultProjectSettings("GG Fizz", "GG Fizz Cluster", "project-uuid"),
  ...over,
});

function input(over: Partial<ValidationInput> = {}): ValidationInput {
  return {
    settings: settings(),
    production: emptyProductionDraft(),
    remaps: emptyRemapsDraft(),
    cosmetics: emptyCosmeticsDraft(),
    catalog: emptyCatalog(),
    players: emptyPlayers(),
    index: null,
    imageFiles: [],
    ...over,
  };
}

const cosmetic = (modId: string, over: Record<string, unknown> = {}) => ({
  id: `record-${modId}`,
  modId,
  enableDynamicDownload: true,
  allowNonDataOnlyBlueprints: true,
  included: true,
  name: `Mod ${modId}`,
  url: "",
  updated: "",
  notes: "",
  deprecatedAt: null,
  ...over,
});

describe("an empty project", () => {
  it("has nothing wrong with it", () => {
    const report = validateProject(input());
    expect(report.errors).toBe(0);
    expect(report.publishable).toBe(true);
  });
});

describe("schema and manifest", () => {
  it("blocks with no project open", () => {
    const report = validateProject(input({ settings: null }));
    expect(report.publishable).toBe(false);
    expect(report.blockedAreas).toContain("schema");
  });

  /** A project this build cannot fully read must not be regenerated by it. */
  it("blocks a project from a schema this build cannot publish", () => {
    const report = validateProject(
      input({ settings: settings({ schemaVersion: 99 as never }) }),
    );
    expect(report.blockedAreas).toContain("schema");
  });

  it("blocks a project with no permanent id or no name", () => {
    expect(
      validateProject(input({ settings: settings({ projectId: "" }) })).blockedAreas,
    ).toContain("manifest");
    expect(
      validateProject(input({ settings: settings({ name: " " }) })).blockedAreas,
    ).toContain("manifest");
  });

  /** A path that escapes would write outside the published tree. */
  it("blocks an output path that leaves the repository", () => {
    for (const bad of ["/etc/passwd", "../outside.json", "a\\b.json", ""]) {
      const report = validateProject(
        input({
          settings: settings({
            outputPaths: { ...settings().outputPaths, production: bad },
          }),
        }),
      );
      expect(report.blockedAreas, bad).toContain("manifest");
    }
  });
});

describe("cosmetics", () => {
  /** The game reads the list top to bottom; a duplicate downloads twice. */
  it("blocks the same mod appearing twice", () => {
    const cosmetics = {
      ...emptyCosmeticsDraft(),
      entries: [cosmetic("1431447"), { ...cosmetic("1431447"), id: "other" }],
    } as unknown as CosmeticsDraft;

    const report = validateProject(input({ cosmetics }));
    expect(report.blockedAreas).toContain("cosmetics");
    expect(issuesFor(report, "cosmetics")[0].message).toContain("1431447");
  });

  it("does not count an excluded entry as a duplicate", () => {
    const cosmetics = {
      ...emptyCosmeticsDraft(),
      entries: [cosmetic("1431447"), { ...cosmetic("1431447"), id: "b", included: false }],
    } as unknown as CosmeticsDraft;
    expect(validateProject(input({ cosmetics })).errors).toBe(0);
  });
});

describe("the catalog", () => {
  const source = (over: Record<string, unknown> = {}) => ({
    id: "s1",
    name: "Ports of Atlas",
    kind: "mod" as const,
    curseforgeId: "972253",
    ...over,
  });

  it("blocks two sources sharing an id", () => {
    const catalog = {
      ...emptyCatalog(),
      sources: [source(), source({ name: "Other" })],
    } as unknown as CatalogFile;
    expect(validateProject(input({ catalog })).blockedAreas).toContain("catalog");
  });

  it("warns about a source with no name", () => {
    const catalog = {
      ...emptyCatalog(),
      sources: [source({ name: "" })],
    } as unknown as CatalogFile;
    const report = validateProject(input({ catalog }));
    expect(report.errors).toBe(0);
    expect(report.warnings).toBe(1);
  });
});

describe("the roster", () => {
  it("blocks two players sharing an id", () => {
    const players = {
      ...emptyPlayers(),
      players: [newPlayer("p1"), newPlayer("p1")],
    } as PlayersFile;
    expect(validateProject(input({ players })).blockedAreas).toContain("players");
  });

  /** Recoverable by re-uploading, so it does not stop a publish. */
  it("warns about a profile reference with no file", () => {
    const players = {
      ...emptyPlayers(),
      players: [
        {
          ...newPlayer("p1"),
          profile: {
            fileName: "",
            storedAt: "",
            map: "",
            backedUpAt: null,
            summary: null,
            generated: false,
            archivedAt: null,
          },
        },
      ],
    } as PlayersFile;
    const report = validateProject(input({ players }));
    expect(report.publishable).toBe(true);
    expect(issuesFor(report, "players")[0].level).toBe("warning");
  });
});

describe("icons", () => {
  const withIcon = (icon: string, imageFiles: string[] = []) =>
    validateProject(
      input({
        catalog: { ...emptyCatalog(), icons: { "/Game/A": icon } } as CatalogFile,
        imageFiles,
      }),
    );

  /** The viewer falls back to an emoji, so the site is plainer, not wrong. */
  it("warns about an icon that is not in the images folder", () => {
    const report = withIcon("file:rex.webp");
    expect(report.publishable).toBe(true);
    expect(issuesFor(report, "assets")[0].message).toContain("rex.webp");
  });

  it("warns about an icon that is not a WebP", () => {
    const report = withIcon("file:rex.png", ["rex.png"]);
    expect(report.warnings).toBe(1);
    expect(issuesFor(report, "assets")[0].message).toContain("slower");
  });

  it("is happy with a WebP that is present", () => {
    expect(withIcon("file:rex.webp", ["rex.webp"]).warnings).toBe(0);
  });

  it("matches the file name whatever the casing", () => {
    expect(withIcon("file:Rex.webp", ["rex.webp"]).warnings).toBe(0);
  });

  it("ignores an emoji icon, which needs no file", () => {
    expect(withIcon("🦖").warnings).toBe(0);
  });
});

describe("the report", () => {
  /** An administrator fixing a project wants the whole list, not one at a time. */
  it("reports every problem at once", () => {
    const report = validateProject(
      input({
        settings: settings({ projectId: "", name: "" }),
        players: { ...emptyPlayers(), players: [newPlayer("p1"), newPlayer("p1")] } as PlayersFile,
      }),
    );
    expect(report.errors).toBeGreaterThanOrEqual(3);
    expect(report.blockedAreas).toContain("manifest");
    expect(report.blockedAreas).toContain("players");
  });

  it("tags every issue with the area it came from", () => {
    const report = validateProject(input({ settings: settings({ name: "" }) }));
    for (const issue of report.issues) expect(issue.area).toBeTruthy();
  });

  it("is publishable when only warnings remain", () => {
    const report = validateProject(
      input({
        catalog: { ...emptyCatalog(), icons: { "/Game/A": "file:missing.webp" } } as CatalogFile,
      }),
    );
    expect(report.publishable).toBe(true);
    expect(report.warnings).toBe(1);
    expect(report.blockedAreas).toEqual([]);
  });
});
