import { z } from "zod";
import { ProfileSummarySchema } from "./profileData";

/**
 * Player roster for the cluster: the handful of identifiers an admin needs to
 * tie a Discord complaint to a Steam account to an in-game character, plus the
 * last .arkprofile taken for that player.
 *
 * Profiles are copied into the project's `profiles/` folder rather than being
 * embedded here - they are binary save data, and a JSON file is the wrong home
 * for them.
 */

/**
 * A profile on disk. Only what the admin actually needs to see: that one is
 * stored, and when - the byte count and origin path were noise.
 */
export const StoredProfileSchema = z.object({
  /**
   * File name inside the project's profiles/ folder. Tolerates being absent:
   * a missing name means the reference is broken and the profile needs
   * re-uploading - which must not cost the admin their whole roster.
   */
  fileName: z.string().default(""),
  storedAt: z.string().default(""),
  /** ASA map the save came from - a profile is per-map, so this matters. */
  map: z.string().default(""),
  /** When this profile was last pushed to GitHub; null = local only. */
  backedUpAt: z.string().nullable().default(null),
  /**
   * What was read out of the file when it was stored. Kept here so the roster
   * can show a survivor's level and tribe without re-reading binary save data,
   * and so those details survive on a machine that no longer has the file.
   * Null for profiles stored before the app could read them.
   */
  summary: ProfileSummarySchema.nullable().default(null),
  /** True when this profile was generated by the app rather than taken from a server. */
  generated: z.boolean().default(false),
  /**
   * When the admin moved this save out of the default roster view. Null while
   * it is current. Archiving never touches the file - see PlayerDataSettings.
   */
  archivedAt: z.string().nullable().default(null),
});
export type StoredProfile = z.infer<typeof StoredProfileSchema>;

export const PlayerSchema = z.object({
  id: z.string(),
  discordName: z.string().default(""),
  /** Discord's numeric snowflake - the part that survives a name change. */
  discordId: z.string().default(""),
  steamName: z.string().default(""),
  /** SteamID64. */
  steamId: z.string().default(""),
  /**
   * Platform account name as ASA records it - a Steam persona, an Xbox
   * gamertag, whatever the account is. Distinct from the survivor's name, and
   * the one identifier a `.arkprofile` can be relied on to carry.
   */
  accountName: z.string().default(""),
  /** In-game survivor name, which often matches neither of the above. */
  gameName: z.string().default(""),
  /** In-game Player ID (the number `ListPlayers` reports). */
  playerId: z.string().default(""),
  /** Epic Online Services id - how ASA identifies the account. */
  eosId: z.string().default(""),
  notes: z.string().default(""),
  profile: StoredProfileSchema.nullable().default(null),
});
export type Player = z.infer<typeof PlayerSchema>;

export type PlayerFieldKey =
  | "discordName"
  | "discordId"
  | "steamName"
  | "steamId"
  | "accountName"
  | "gameName"
  | "playerId"
  | "eosId";

export interface PlayerFieldSpec {
  key: PlayerFieldKey;
  label: string;
  hint?: string;
  mono?: boolean;
  placeholder?: string;
}

/** Every identifier, in edit-form order. Also what the search box covers. */
export const PLAYER_FIELDS: PlayerFieldSpec[] = [
  {
    key: "discordName",
    label: "Discord name",
    placeholder: "e.g. survivor or @survivor",
  },
  {
    key: "discordId",
    label: "Discord ID",
    hint: "Numeric - survives a rename",
    mono: true,
    placeholder: "e.g. 218450941836787712",
  },
  { key: "steamName", label: "Steam name" },
  { key: "steamId", label: "Steam ID", hint: "SteamID64", mono: true },
  {
    key: "accountName",
    label: "Account name",
    hint: "Platform name the .arkprofile records",
  },
  { key: "gameName", label: "Game name", hint: "In-game survivor name" },
  {
    key: "playerId",
    label: "Player ID",
    hint: "The number ListPlayers reports",
    mono: true,
  },
  {
    key: "eosId",
    label: "EOS ID",
    hint: "How ASA identifies the account",
    mono: true,
    placeholder: "0002abcd…",
  },
];

/**
 * The read view's grouping: a platform's name and its id belong on one line,
 * because you almost always want them together.
 */
export interface PlayerFieldRow {
  label: string;
  nameKey?: PlayerFieldKey;
  idKey: PlayerFieldKey;
}

export const PLAYER_ROWS: PlayerFieldRow[] = [
  { label: "Discord", nameKey: "discordName", idKey: "discordId" },
  { label: "Steam", nameKey: "steamName", idKey: "steamId" },
  { label: "Game", nameKey: "gameName", idKey: "playerId" },
  // The account name and the EOS id are the pair a profile carries, so they
  // read together the same way the platform rows do.
  { label: "Account", nameKey: "accountName", idKey: "eosId" },
];

/** Names a player can be recognised by, for the identifier pickers. */
export const PLAYER_NAME_KEYS: PlayerFieldKey[] = [
  "discordName",
  "gameName",
  "steamName",
  "accountName",
];

/**
 * A "clean slate" profile kept for rebuilding lost characters: a fresh spawn
 * with no points spent, default appearance and nothing learned.
 *
 * One per map, because a profile is per-map save data and the newer maps use a
 * save format the older ones cannot read. Stored in the project's profiles/
 * folder like any other, under a reserved name.
 */
export const CleanSlateSchema = z.object({
  /** Map name, matching the Maps setting. */
  map: z.string().default(""),
  /** File name inside the project's profiles/ folder. */
  fileName: z.string().default(""),
  addedAt: z.string().default(""),
  summary: ProfileSummarySchema.nullable().default(null),
});
export type CleanSlate = z.infer<typeof CleanSlateSchema>;

export const PlayersFileSchema = z.object({
  schemaVersion: z.literal(1),
  players: z.array(PlayerSchema).default([]),
  /** Blank starting profiles, keyed by nothing - the map lives on each entry. */
  cleanSlates: z.array(CleanSlateSchema).default([]),
});
export type PlayersFile = z.infer<typeof PlayersFileSchema>;

export function emptyPlayers(): PlayersFile {
  return { schemaVersion: 1, players: [], cleanSlates: [] };
}

/** The clean slate registered for a map, if there is one. */
export function cleanSlateFor(file: PlayersFile, map: string): CleanSlate | undefined {
  const key = map.trim().toLowerCase();
  return file.cleanSlates.find((s) => s.map.trim().toLowerCase() === key);
}

/** Reserved profiles/ file name for a map's clean slate. */
export function cleanSlateFileName(map: string): string {
  const safe = map.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return `clean-slate-${safe || "map"}`;
}

export function newPlayer(id: string): Player {
  return {
    id,
    discordName: "",
    discordId: "",
    steamName: "",
    steamId: "",
    accountName: "",
    gameName: "",
    playerId: "",
    eosId: "",
    notes: "",
    profile: null,
  };
}

/**
 * Players that have a value for the requested identifier, paired with a name
 * to show. Drives the pickers on fields elsewhere in the app, so a roster
 * entry can be chosen instead of a number being typed from memory.
 */
export function playerChoices(
  players: Player[],
  field: PlayerFieldKey,
): { player: Player; label: string; value: string; aka: string }[] {
  return players
    .filter((p) => p[field].trim())
    .map((p) => {
      const names = PLAYER_NAME_KEYS.map((k) => p[k].trim()).filter(Boolean);
      return {
        player: p,
        label: names[0] || playerLabel(p),
        // Every other name they go by, so searching any of them finds them.
        aka: names.slice(1).join(" · "),
        value: p[field].trim(),
      };
    })
    .sort((a, b) => a.label.localeCompare(b.label));
}

/** Best label for a player row - whichever identifier they actually filled in. */
export function playerLabel(player: Player): string {
  return (
    player.discordName.trim() ||
    player.gameName.trim() ||
    player.steamName.trim() ||
    player.accountName.trim() ||
    player.playerId.trim() ||
    player.eosId.trim() ||
    "(unnamed player)"
  );
}

/**
 * A profile reference that lost its file name - the file on disk can no
 * longer be found, so it has to be uploaded again.
 */
export function profileIsBroken(profile: StoredProfile | null): boolean {
  return profile !== null && !profile.fileName.trim();
}

/** True once the record carries anything worth keeping. */
export function hasPlayerDetails(player: Player): boolean {
  return (
    PLAYER_FIELDS.some((f) => player[f.key].trim()) || Boolean(player.notes.trim())
  );
}

/**
 * Matches a player against a search box across every identifier, since an
 * admin will have exactly one of them to hand when they come looking.
 *
 * The stored profile's map is searchable too - "who do I have on Ragnarok"
 * is a question the roster should answer, and the map is not one of the
 * identifier fields.
 */
export function playerMatches(player: Player, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  const haystack = [
    ...PLAYER_FIELDS.map((f) => player[f.key]),
    player.notes,
    player.profile?.map ?? "",
    player.profile?.summary?.mapPackage ?? "",
  ];
  return haystack.some((field) => field.toLowerCase().includes(q));
}

/**
 * Roster order: by the name each row actually shows, case-insensitively.
 *
 * Sorting by the displayed label rather than a fixed field keeps the list in
 * the order it reads in - sorting by, say, Discord name would scatter the
 * entries that have none.
 */
export function comparePlayers(a: Player, b: Player): number {
  return playerLabel(a).localeCompare(playerLabel(b), undefined, {
    sensitivity: "base",
    numeric: true,
  });
}

/** Distinct maps across the roster's stored profiles, for the map filter. */
export function rosterMaps(players: Player[]): string[] {
  const maps = new Set<string>();
  for (const player of players) {
    const map = player.profile?.map.trim();
    if (map) maps.add(map);
  }
  return [...maps].sort((a, b) => a.localeCompare(b));
}
